### Variables
@hostname = localhost
@port = 8080
@host = {{hostname}}:{{port}}
@accept= application/vnd.api+json;version=1


### Get by Accept header
GET /api/customers HTTP/1.1
Host: {{host}}
Accept: {{accept}}


### Get by URL version 1
GET /api/v1/customers HTTP/1.1
Host: {{host}}

### Get by URL version 2
GET /api/v2/customers HTTP/1.1
Host: {{host}}